#! /bin/sh
#
### BEGIN INIT INFO
# Provides:           querierd
# Required-Start:     $network $local_fs $syslog
# Required-Stop:      0 1 6
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description: Emulate a multicast router so avahi will work.
# Description: Sends an IGMP query packet at a specified interval.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=querierd
DESC="IGMP querier daemon"
CONFIG=/etc/querierd

test -e $CONFIG || exit 0

set -e

case "$1" in
  start)
	exec python -m querier.daemon start
	;;
  stop)
	exec python -m querier.daemon stop
	;;
  restart)
	exec python -m querier.daemon restart
	;;
  status)
	if [ -s /var/run/$NAME.pid ]; then
            RUNNING=$(cat /var/run/$NAME.pid)
            if [ -d /proc/$RUNNING ]; then
                if [ $(readlink /proc/$RUNNING/exe) = $DAEMON ]; then
                    echo "$NAME is running."
                    exit 0
                fi
            fi

            # No such PID, or executables don't match
            echo "$NAME is not running, but pidfile existed."
            rm /var/run/$NAME.pid
            exit 1
        else
            rm -f /var/run/$NAME.pid
            echo "$NAME not running."
            exit 1
        fi
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
